
plugins {
    id("java")
}

group = "com.erling"
version = "0.0.1-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':Controller-J')
//    implementation project(':Controller-J')
    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
}
bootJar {
    mainClass = 'com.erling.Application' // 替换为你的主类全限定名
}
tasks.test {
    useJUnitPlatform()
}