/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_erling_nativeJ_opencvJni_libinterface_basic_image__EdgeDetectionJni */

#ifndef _Included_com_erling_nativeJ_opencvJni_libinterface_basic_image__EdgeDetectionJni
#define _Included_com_erling_nativeJ_opencvJni_libinterface_basic_image__EdgeDetectionJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_erling_nativeJ_opencvJni_libinterface_basic_image__EdgeDetectionJni
 * Method:    CannyJNI
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;DDI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_erling_nativeJ_opencvJni_libinterface_basic_image__1EdgeDetectionJni_CannyJNI
  (JNIEnv *, jobject, jobject, jstring, jdouble, jdouble, jint);

/*
 * Class:     com_erling_nativeJ_opencvJni_libinterface_basic_image__EdgeDetectionJni
 * Method:    SobelJNI
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;IDIDDI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jbyteArray JNICALL Java_com_erling_nativeJ_opencvJni_libinterface_basic_image__1EdgeDetectionJni_SobelJNI
  (JNIEnv *, jobject, jbyteArray, jstring, jint, jdouble, jint, jdouble, jdouble, jint);
/*
 * Class:     com_erling_nativeJ_opencvJni_libinterface_basic_image__EdgeDetectionJni
 * Method:    LaplacianJNI
 * Signature: (Ljava/nio/ByteBuffer;DDI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_erling_nativeJ_opencvJni_libinterface_basic_image__1EdgeDetectionJni_LaplacianJNI
  (JNIEnv *, jobject, jobject, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
