/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_erling_nativeJ_opencvJni_libinterface_basic_EdgeDetectionJni */

#ifndef _Included_com_erling_nativeJ_opencvJni_libinterface_basic_EdgeDetectionJni
#define _Included_com_erling_nativeJ_opencvJni_libinterface_basic_EdgeDetectionJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_erling_nativeJ_opencvJni_libinterface_basic_EdgeDetectionJni
 * Method:    ADD
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_erling_nativeJ_opencvJni_libinterface_basic_EdgeDetectionJni_ADD
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_erling_nativeJ_opencvJni_libinterface_basic_EdgeDetectionJni
 * Method:    TestCanny
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_erling_nativeJ_opencvJni_libinterface_basic_EdgeDetectionJni_TestCanny
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_erling_nativeJ_opencvJni_libinterface_basic_EdgeDetectionJni
 * Method:    TestNoCudaCanny
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_erling_nativeJ_opencvJni_libinterface_basic_EdgeDetectionJni_TestNoCudaCanny
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
